### PR TITLE
fix(sbb-tag): fix styles

### PR DESCRIPTION
**Pull request by federicoisepponfincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR fixes an issue reported by Aleksandar from team Lynx, related to both storybook and his aem environment:
Tag elements are not correctly displayed

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- fixed tag element display (background, border, animations)

## Browsers

I tested the build on the following browsers:

- [x] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [x] Safari Desktop
- [x] Chrome Mobile
- [x] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kyubisation — CHANGES_REQUESTED** [review]
The ellipsis seem to be broken

**Comment by federicoisepponfincons** [comment]
> The ellipsis seem to be broken

working on it

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]
- active state is wrong now (should be small again when pressing)
- focus outline seems not to work

**Comment by federicoisepponfincons** [comment]
pushed fixes for ellipsis + active state + focus outline + minor bug on firefox

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks

**Review by kyubisation — APPROVED** [review]
LGTM 👍

**Pull request merged**
