### PR TITLE
fix: stories with label bold for sbb-checkbox and sbb-radio-button

### LINKED ISSUE #2498: Feature: Checkbox/Radiobutton with bold example
For specific use cases a checkbox/radio button with bold text is needed. This is already possible to do with the CSS class `sbb-text--bold`.

Add a story with the following example:
```html
<sbb-checkbox>
  <span class="sbb-text--bold">Bold Label</span>
</sbb-checkbox>
```

Add a story with the following example:
```html
<sbb-radio-button>
  <span class="sbb-text--bold">Bold Label</span>
</sbb-radio-button>
```

Needed for ÖVG:
https://www.figma.com/file/BS4MP1EC7Fb22MgcWtwlOX/07%3A-Design-%E2%80%93-%C3%96V-Guthaben?type=design&node-id=9425-785431&t=HahdDz3Wy73Beksr-0

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #2498 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../REVIEW.md) for more information what is checked during review process.

## Changes

Changes in this pull request:

- add stories with bold label for sbb-checkbox and sbb-radio-button

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jeripeierSBB — APPROVED** [review]
LGTM, not sure if we need also an entry in readme files?

**Review by TomMenga — APPROVED** [review]
LGTM 👍 

I'm not sure if having the `bold` param in storybook might be confusing (they might think there is a `bold` attribute)
Maybe add an example in the readme?

**Comment by DavideMininni-Fincons** [comment]
@TomMenga @jeripeierSBB 
i'll add a note in the readme; maybe i can change the bold param with something like 'boldLabel'?

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks for re working

**Pull request merged**
